name: "AWS Terragrunt PR Plan"

on:
  workflow_call:
    inputs:
      CONTAINER:
        required: false
        type: string
        default: ghcr.io/liatrio/builder-image-aws-terraform:v1.0.5
      WORKING_DIR:
        required: false
        type: string
        default: ./
      AWS_OIDC_ROLE_ARN:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      ROLE_SESSION_NAME:
        required: false
        type: string
        default: github-action_aws-terragrunt-pr-plan-oidc
      ROLE_DURATION_SECTIONS:
        required: false
        type: number
        default: 1200 # 20 min

jobs:
  aws-terragrunt-pr-plan:
    name: "AWS Terragrunt PR Plan"
    runs-on: ubuntu-latest
    container: ${{ inputs.CONTAINER }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
      actions: write
      packages: read # This is required for the workflow to pull a container
      pull-requests: write # This is required by liatrio/terrafrom-chage-pr-commenter
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.AWS_REGION }}
          role-to-assume: ${{ inputs.AWS_OIDC_ROLE_ARN }}
          role-session-name: ${{ inputs.ROLE_SESSION_NAME }}
          role-duration-seconds: ${{ inputs.ROLE_DURATION_SECTIONS }}

      - name: Terragrunt hcl check
        run: terragrunt hclfmt --terragrunt-check

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terragrunt validate check
        run: terragrunt run-all validate --terragrunt-non-interactive

      - name: Terragrunt Plan
        id: terragrunt_plan
        run: |
          terragrunt plan --terragrunt-non-interactive -out plan.out
          terragrunt show --terragrunt-non-interactive -no-color -json plan.out > plan.json
        continue-on-error: true # Continue on error to ensure the plan is added as a comment on the PR.

      - uses: liatrio/terraform-change-pr-commenter@v1.3.2
        with:
          json-file: ${{ inputs.WORKING_DIR }}/plan.json

      - name: Status
        if: contains(steps.*.outcome, 'failure')
        run: exit 1
